name: panorama
description: Panorama -- A 360-degree panorama viewer.
version: 0.4.1
homepage: https://github.com/zesage/panorama

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_cube: ^0.1.1
  motion_sensors:
    git:
      url: https://github.com/zesage/motion_sensors.git
      ref: 6dafc36 # commit hash

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
